### PR TITLE
[88] Fixed flackyness in EagerQbftBlockCreator test

### LINKED ISSUE #88: Flacky test in EagerQbftBlockCreatorTest
## Impact
__environment [CI]__

__an user is impacted [Y], if yes type of user: [Internal]__

## Describe the bug
The test `EagerQbftBlockCreatorTest > can create a non empty block with new timestamp` is flacky, [run](https://github.com/Consensys/maru/actions/runs/14748501199/job/41400386230)

### Steps to Reproduce
No consistent way to reproduce it

### PR DESCRIPTION
**Pull request by Filter94**
(Hopefully) Fixes #88

### CODE REVIEW

File: consensus/src/test/kotlin/maru/consensus/qbft/EagerQbftBlockCreatorTest.kt [hunk 1]
```diff
@@ -225,8 +312,35 @@ class EagerQbftBlockCreatorTest {
...
+    executionLayerManager.setHeadAndStartBlockBuilding(
+      headHash = genesisBlockHash,
+      safeHash = genesisBlockHash,
+      finalizedHash = genesisBlockHash,
+      nextBlockTimestamp = rejectedBlockTimestamp,
+      feeRecipient = validator.address,
+    )
+    val transaction = TransactionsHelper().createTransfers(1u)
+    besuInstance.execute(transaction)
+    Thread.sleep(1000)
```
Comment (gauravahuja) [inline consensus/src/test/kotlin/maru/consensus/qbft/EagerQbftBlockCreatorTest.kt:335]: Why is this sleep needed?

**Review by gauravahuja — APPROVED** [review]

File: consensus/src/test/kotlin/maru/consensus/qbft/EagerQbftBlockCreatorTest.kt [hunk 2]
```diff
@@ -99,29 +93,43 @@ class EagerQbftBlockCreatorTest {
...
-        .toDomain()
-    val parentBlock =
-      BeaconBlock(
-        beaconBlockHeader = DataGenerators.randomBeaconBlockHeader(0U),
-        beaconBlockBody =
-          DataGenerators
-            .randomBeaconBlockBody()
-            .copy(executionPayload = genesisExecutionPayload),
+  @BeforeEach
+  fun beforeEach() {
```
Comment (gauravahuja) [inline consensus/src/test/kotlin/maru/consensus/qbft/EagerQbftBlockCreatorTest.kt:98]: Doesn't instantiating these variables before each test limit how the tests can be run in parallel. Since these are shared variables, this test suite cannot run multiple tests in separate threads concurrently?

File: consensus/src/test/kotlin/maru/consensus/qbft/EagerQbftBlockCreatorTest.kt (hunk 1 above)
Comment (Filter94) [reply consensus/src/test/kotlin/maru/consensus/qbft/EagerQbftBlockCreatorTest.kt:335]: To give Besu time to build a block. If we call `mainBlockCreator.createBlock` right away, it will build an empty block, which is as good as not trying to build any blocks before the test at all

File: consensus/src/test/kotlin/maru/consensus/qbft/EagerQbftBlockCreatorTest.kt (hunk 2 above)
Comment (Filter94) [reply consensus/src/test/kotlin/maru/consensus/qbft/EagerQbftBlockCreatorTest.kt:98]: That's generally a very good point, but this isn't a pressing issue ATM. Our current target is 8 minutes for the CI run and we're well within that goal. I won't spend more time on it in this PR, but I'll try to keep it in mind for the future.

Comment (Filter94) [reply consensus/src/test/kotlin/maru/consensus/qbft/EagerQbftBlockCreatorTest.kt:98]: After a more careful look what you say is true only if we enable 1 test instance per multiple threads, which is not the default https://www.baeldung.com/junit-testinstance-annotation#test-instance. By Default it's 1 instance per test and I don't really see a reason why would we want 1 instance per process, since we don't manage any expensive resources in memory
