### PR TITLE
Fixed the flacky discovery test

### LINKED ISSUE #234: Flacky Test - P2PTest
- 2025-07-24 [Job run](https://github.com/Consensys/maru/actions/runs/16483092852/job/46652763423?pr=233)

```
P2PTest > peer can be discovered and disconnected peers can be rediscovered() FAILED
    org.opentest4j.AssertionFailedError: 
    Expecting value to be true but was false
        at app//maru.p2p.P2PTest.assertNetworkIsConnectedToPeer(P2PTest.kt:812)
        at app//maru.p2p.P2PTest.peer_can_be_discovered_and_disconnected_peers_can_be_rediscovered$lambda$34(P2PTest.kt:765)
        at app//maru.p2p.P2PTest.awaitUntilAsserted$lambda$40(P2PTest.kt:803)
```

- 2025-07-24 [job run](https://github.com/Consensys/maru/actions/runs/16499539667/job/46653998163)

```
P2PTest > peer can be discovered and disconnected peers can be rediscovered() FAILED
    org.opentest4j.AssertionFailedError: 
    Expecting value to be true but was false
        at app//maru.p2p.P2PTest.assertNetworkIsConnectedToPeer(P2PTest.kt:812)
        at app//maru.p2p.P2PTest.peer_can_be_discovered_and_disconnected_peers_can_be_rediscovered$lambda$34(P2PTest.kt:765)
        at app//maru.p2p.P2PTest.awaitUntilAsserted$lambda$40(P2PTest.kt:803)

P2PTest > static peers can be removed() STANDARD_OUT
    [INFO ] 2025-07-24 14:24:41.592 [ForkJoinPool-1-worker-1] LibP2PNetwork - Starting libp2p network...
    [INFO ] 2025-07-24 14:24:41.594 [ForkJoinPool-1-worker-1] LibP2PNetwork - Starting libp2p network...
    [INFO ] 2025-07-24 14:24:41.594 [nioEventLoopGroup-44-1] teku-status-log - Listening for connections on: /ip4/127.0.0.1/tcp/9234
    [INFO ] 2025-07-24 14:24:41.595 [nioEventLoopGroup-44-1] P2PNetworkImpl$log$1 - Starting P2P network. port=9234, nodeId=16Uiu2HAmPRfinavM2jE9BSkCagBGStJ2SEkPPm6fxFVMdCQebzt6
    [INFO ] 2025-07-24 14:24:41.595 [nioEventLoopGroup-46-1] teku-status-log - Listening for connections on: /ip4/127.0.0.1/tcp/9235
    [INFO ] 2025-07-24 14:24:41.595 [nioEventLoopGroup-46-1] P2PNetworkImpl$log$1 - Starting P2P network. port=9235, nodeId=16Uiu2HAmVXtqhevTAJqZucPbR2W4nCMpetrQASgjZpcxDEDaUPPt
    [INFO ] 2025-07-24 14:24:41.813 [pool-3-thread-1] MaruPeerManager$log$1 - Currently connected peers: []
```

### PR DESCRIPTION
**Pull request by Filter94**
Fixes #234

* The most important item. Fixed resource leak in `MaruPeerManager`. Under some circumstances it just kept creating new threads infinitely, spawning `searchForPeersUntilMaxReached()` calls. This eats up all the available resources and halts the peer discovery. It could have impacted the other tests too.
* Fixed the logging issue. `this::javaClass` evaluates to something like `com.company.Class$log1$nonsense`. I replaced all entries of it with `this.javaClass`, which evaluates to the expected `com.company.Class`
* Introduced a refresh interval configuration for the Discovery service
* Added a validation to MaruDiscoveryService to validate that discovery service isn't null
* Fixed an issue that `MaruDiscoveryService#getKnownPeers` sometimes returns duplicate records. Implemented deduplication with a `toSet()`
* Reduced log spam from `MaruDiscoveryService`
* Improved some logging in `MaruPeerManager`
* Minor refactoring of `P2PTest#peer can be discovered and disconnected peers can be rediscovered` test
* Added DEBUG logs for P2P tests in p2p module

### CODE REVIEW

File: p2p/src/main/kotlin/maru/p2p/MaruPeerManager.kt [hunk 1]
```diff
@@ -98,12 +99,13 @@ class MaruPeerManager(
   init {
     scheduler.scheduleAtFixedRate({
       logConnectedPeers()
-    }, 30, 30, TimeUnit.SECONDS)
+    }, 30, 30000, TimeUnit.SECONDS)
```
[the remark this answers is not in the document]
Comment (fluentcrafter) [reply p2p/src/main/kotlin/maru/p2p/MaruPeerManager.kt:102]: @Filter94 this seems legit. Can you take a look into it?

Also, unrealed but since you are hands on it, can you move `connectedPeers` and `init {` above close to ther declarations, before instance methods?

File: p2p/src/main/kotlin/maru/p2p/MaruPeerManager.kt [hunk 2]
```diff
@@ -152,26 +154,32 @@ class MaruPeerManager(
         if (p2pNetwork.peerCount >= maxPeers || connectionInProgress.contains(peer.nodeIdBytes)) {
           return
         }
-        connectionInProgress.add(peer.nodeIdBytes!!)
+        connectionInProgress.add(peer.nodeIdBytes)
       }
 
-      log.debug("Peer {} Connecting to peer {}...", discoveryService!!.getLocalNodeRecord().nodeId, peer.nodeIdBytes)
+      log.debug("peer={} Connecting to peer={}...", discoveryService!!.getLocalNodeRecord().nodeId, peer.nodeIdBytes)
```
Comment (fluentcrafter) [inline p2p/src/main/kotlin/maru/p2p/MaruPeerManager.kt:160]:
```suggestion
      log.debug("peer={} connecting to peer={}...", discoveryService!!.getLocalNodeRecord().nodeId, peer.nodeIdBytes)
```

File: p2p/src/main/kotlin/maru/p2p/MaruPeerManager.kt [hunk 3]
```diff
@@ -152,26 +154,32 @@ class MaruPeerManager(
...
       p2pNetwork
         .connect(p2pNetwork.createPeerAddress(peer))
         .orTimeout(30, TimeUnit.SECONDS)
         .whenComplete { _, throwable ->
           try {
             if (throwable != null) {
-              log.debug("Failed to connect to peer {}: {}", peer.nodeIdBytes, throwable.stackTraceToString())
+              log.error("Failed to connect to peer ${peer.nodeIdBytes}", throwable)
```
Comment (fluentcrafter) [inline p2p/src/main/kotlin/maru/p2p/MaruPeerManager.kt:167]: please favour placeholders. 

```suggestion
              log.error("Failed to connect to peer={}", peer.nodeIdBytes,  throwable)
```

File: p2p/src/main/kotlin/maru/p2p/MaruPeerManager.kt [hunk 4]
```diff
@@ -152,26 +154,32 @@ class MaruPeerManager(
...
             }
           } finally {
             synchronized(connectionInProgress) {
               connectionInProgress.remove(peer.nodeIdBytes)
             }
           }
         }
+      log.debug(
+        "peer={} Finished connecting to peer={}...",
```
Comment (fluentcrafter) [inline p2p/src/main/kotlin/maru/p2p/MaruPeerManager.kt:176]:
```suggestion
        "peer={} connected to peer={}",
```

File: p2p/src/main/kotlin/maru/p2p/MaruPeerManager.kt [hunk 5]
```diff
@@ -152,26 +154,32 @@ class MaruPeerManager(
...
+        discoveryService!!.getLocalNodeRecord().nodeId,
+        peer
+          .nodeIdBytes,
+      )
     } catch (e: Exception) {
-      log.debug("Failed to initiate connection to peer {}: {}", peer.nodeIdBytes, e.stackTraceToString())
+      log.debug("Failed to initiate connection to peer={}: {}", peer.nodeIdBytes, e.stackTraceToString())
```
Comment (fluentcrafter) [inline p2p/src/main/kotlin/maru/p2p/MaruPeerManager.kt:182]:
```suggestion
      log.debug("Failed to initiate connection to peer={}. errorMessage={}", peer.nodeIdBytes, e.message, e)
```

**Review by fluentcrafter — APPROVED** [review]

**Review by fluentcrafter — APPROVED** [review]
